### ISSUE TITLE
six is already installed beginning with el-capitan 

### ISSUE THREAD

**Issue by raam86** [FindHotel/s3keyring#6]
So trying to install using pip I got:
`OSError: [Errno 1] Operation not permitted: '/tmp/pip-wmni7i-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`
This issue talks about it:
https://github.com/pypa/pip/issues/3165

solution: 
`sudo -H pip install --ignore-installed  git+https://github.com/InnovativeTravel/s3-keyring`

**Comment by germangh** [comment]
Thanks for reporting this and posting a solution. I would strongly recommend leaving the Python installation that comes with Mac OS alone and install a completely separate Python for development. This should do it:

```
brew install python
```

I'll add a not in the repo doc warning about this.
